export interface User {
    id?: string;          // Optional field for user ID (if it's auto-generated by backend)
    email: string;
    password: string;
    id_number: string;
    user_type: string;
    firstname: string;
    lastname: string;
    comment: string;
  }
  